repos:
- repo: local
  hooks:
    - id: cargo-fmt
      name: Format
      description: Format files with cargo fmt.
      entry: cargo +nightly fmt
      language: system
      types: [rust]
      args: ["--"]
    - id: cargo-check
      name: Check
      description: Check the package for errors.
      entry: cargo check
      language: system
      args: ["--workspace"]
      types: [rust]
      pass_filenames: false
    - id: cargo-clippy
      name: Lint
      description: Lint rust sources
      entry: cargo clippy
      language: system
      args: ["--", "-D", "warnings"]
      types: [rust]
      pass_filenames: false
    - id: cargo-test
      name: Test
      description: Test rust sources and check coverage
      entry: cargo llvm-cov
      language: system
      args:
        - "--ignore-filename-regex"
        - "error|default|traits"
        - "-q"
        - "--fail-under-lines"
        - "80"
        - "--html"
      types: [rust]
      pass_filenames: false